Repository Zagabi-LikeLion/BackEnd, pull requests merged in 2024-07, with the labels that each got.

#14 ✨feat: Diary API 개발(인증/인가 부분 제외) (#9)
  src/main/java/org/likelion/zagabi/Domain/Diary/Controller/DiaryController.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Request/DiaryRequestDto.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Request/UpdateDiaryRequestDto.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Response/DiaryQuestionResponseDto.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Response/DiaryResponseDto.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Response/DiarySummaryDto.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Entity/Diary.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Entity/DiaryQuestion.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Entity/Enums/Mood.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Repository/DiaryQuestionRepository.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Repository/DiaryRepository.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Service/DiaryQueryService.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Service/DiaryService.java
  src/main/java/org/likelion/zagabi/ZagabiApplication.java
  src/main/resources/application.yml
Labels: feature

#17 ♻️refactor: 카테고리와 가치관 연결
  src/main/java/org/likelion/zagabi/Domain/Category/Service/ValueCategoryService.java
  src/main/java/org/likelion/zagabi/Domain/Value/Repository/ValueRepository.java
Labels: refactor

#23 [Feature] 인증&인가 최종구현 및 스웨거 적용 완료
  src/main/java/org/likelion/zagabi/Domain/Account/Controller/AccountController.java
  src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/ChangeNicknameRequestDto.java
  src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/ChangePwRequestDto.java
  src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/ForgotPwRequestDto.java
  src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/UserSignUpRequestDto.java
  src/main/java/org/likelion/zagabi/Domain/Account/Entity/User.java
  src/main/java/org/likelion/zagabi/Domain/Account/Jwt/Exception/JwtAuthenticationEntryPoint.java
  src/main/java/org/likelion/zagabi/Domain/Account/Jwt/Filter/JwtAuthenticationFilter.java
  src/main/java/org/likelion/zagabi/Domain/Account/Jwt/UserDetails/CustomUserDetails.java
  src/main/java/org/likelion/zagabi/Domain/Account/Jwt/Util/JwtProvider.java
  src/main/java/org/likelion/zagabi/Domain/Account/Repository/UserJpaRepository.java
  src/main/java/org/likelion/zagabi/Domain/Account/Service/AccountService.java
  src/main/java/org/likelion/zagabi/Domain/Account/Service/UserService.java
  src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Entity/ValueTrashCan.java
  src/main/java/org/likelion/zagabi/Global/Config/CorsConfig.java
  src/main/java/org/likelion/zagabi/Global/Config/SecurityConfig.java
  src/main/java/org/likelion/zagabi/Global/Config/SwaggerConfig.java
Labels: feature

#28 ♻️refactor: Account 부분 role 값 삭제 및 코드 리팩토링 (#25)
  src/main/java/org/likelion/zagabi/Domain/Account/Controller/AccountController.java
  src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/ChangeNicknameRequestDto.java
  src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/UserSignUpRequestDto.java
  src/main/java/org/likelion/zagabi/Domain/Account/Entity/User.java
  src/main/java/org/likelion/zagabi/Domain/Account/Jwt/Filter/JwtAuthenticationFilter.java
  src/main/java/org/likelion/zagabi/Domain/Account/Jwt/UserDetails/CustomUserDetails.java
  src/main/java/org/likelion/zagabi/Domain/Account/Service/AccountService.java
Labels: refactor

#27 [FEATURE] 토큰 재발급 기능 구현
  src/main/java/org/likelion/zagabi/Domain/Account/Controller/AccountController.java
  src/main/java/org/likelion/zagabi/Global/Config/SecurityConfig.java
Labels: feature

#30 [FIX] Admin 관련 필요없는 코드 제거
  src/main/java/org/likelion/zagabi/Domain/Account/Controller/AccountController.java
  src/main/java/org/likelion/zagabi/Domain/Account/Jwt/Util/JwtProvider.java
Labels: fix

#32 [REFACTOR] accountController에서성공 시, 메세지 출력되도록 구현 완료
  src/main/java/org/likelion/zagabi/Domain/Account/Controller/AccountController.java
Labels: refactor

#37 [FEATURE] 보안 질문 엔티티 추가
  .gitignore
  src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/UserSignUpRequestDto.java
  src/main/java/org/likelion/zagabi/Domain/Account/Entity/SecurityQuestion.java
  src/main/java/org/likelion/zagabi/Domain/Account/Entity/User.java
  src/main/java/org/likelion/zagabi/Domain/Account/Repository/SecurityQuestionRepository.java
  src/main/java/org/likelion/zagabi/Domain/Account/Service/AccountService.java
Labels: feature

#34 ♻️refactor: 일기 API와 인증/인가 부분 연결 (#22)
  src/main/java/org/likelion/zagabi/Domain/Account/Jwt/UserDetails/CustomUserDetails.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Controller/DiaryController.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Request/DiaryRequestDto.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Request/UpdateDiaryRequestDto.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Entity/Diary.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Repository/DiaryRepository.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Service/DiaryQueryService.java
  src/main/java/org/likelion/zagabi/Domain/Diary/Service/DiaryService.java
Labels: refactor

#38 ♻️refactor: ValueCategory와 인증/인가 부분 연결 (#36)
  src/main/java/org/likelion/zagabi/Domain/Category/Controller/ValueCategoryController.java
  src/main/java/org/likelion/zagabi/Domain/Category/Entity/ValueCategory.java
  src/main/java/org/likelion/zagabi/Domain/Category/Repository/ValueCategoryRepository.java
  src/main/java/org/likelion/zagabi/Domain/Category/Service/ValueCategoryQueryService.java
  src/main/java/org/likelion/zagabi/Domain/Category/Service/ValueCategoryService.java
Labels: refactor

#46 🐛fix: 로그아웃 시 Refresh토큰 blacklist 처리 (#45)
  src/main/java/org/likelion/zagabi/Domain/Account/Controller/AccountController.java
  src/main/java/org/likelion/zagabi/Domain/Account/Jwt/Filter/JwtAuthenticationFilter.java
  src/main/java/org/likelion/zagabi/Domain/Account/Jwt/Util/JwtProvider.java
  src/main/java/org/likelion/zagabi/Domain/Account/Service/AccountService.java
Labels: fix
